name: cheers_app
description: "Flutter app to search for local breweries"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  logger: ^1.1.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.4
  provider: ^6.1.2

flutter:
  uses-material-design: true
